theme: jekyll-theme-cayman
title:"Fast Detection of Brains with Abnormalities Using Recursive Nearest Agglomerative Clustering"
*This project has been presented in OHBM conference as poster presentation
